services:
  - type: web
    name: trueamin-telegram-bot
    env: python
    region: frankfurt
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    plan: free
    envVars:
      - key: BOT_TOKEN
        value: <7345061819:AAF1T7zECDOiBGawR7Oq7zjNriVMpeTdtJk>
